name: C/C++ CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: c++ --version
      run: c++ --version
    - name: make exprtk_test
      run: make exprtk_test
    - name: exprtk_test
      run: ./bin/exprtk_test
    - name: make example
      run: make example
    - name: make build
      run: make build
